### ISSUE TITLE
我其他的应该都弄好了，但翻译还是显示 TypeError: Failed to fetch

### ISSUE THREAD

**Issue by zxiaowwqqwq** [symant233/MTool_Cracker#1]
没搞懂是哪一步弄错了

**Comment by symant233** [comment]
啊？？？¿

**Comment by symant233** [comment]
你是在哪看到这个的，用的是最新版mtool还是我放release里的存档？

**Comment by symant233** [comment]
你是在哪看到这个的，用的是最新版mtool还是我放release里的存档？

**Comment by zxiaowwqqwq** [comment]
我用的是你发的这个MTool_A10U13，查gpt翻译的时候听人提过

**Comment by symant233** [comment]
你这个..报错信息？是在哪里看的，有没有截图什么的。

**Comment by zxiaowwqqwq** [comment]
我是在最后一步尝试翻译游戏的时候报错的 https://jpg.fishing/img/2023-04-24-170845.A2YjLP 这个是图床网址

**Comment by symant233** [comment]
这步做了吗，感觉是这个的问题，搞完重启一下mtool和游戏
> 首次使用此项目时, 由于使用了自签证书, 请求会失败 (更新那里会显示 Failed to fetch). 在工具里右键空白处点击检查, 在 Console 标签页会显示红色的报错, 点链接, 选显示更多继续访问. 之后只要不再换证书就不会再请求失败了.

**Comment by zxiaowwqqwq** [comment]
这步做了，做完后这效果https://jpg.fishing/img/2023-04-24-172344.A260bW     https://jpg.fishing/img/2023-04-24-172359.A26gnd

**Comment by symant233** [comment]
显示没有更新应该可以用了

**Comment by zxiaowwqqwq** [comment]
尝试翻译的时候就会报错

**Comment by symant233** [comment]
> 尝试翻译的时候就会报错

看下终端的报错信息🤔 还有图片可以直接在Github这个输入框Ctrl+V粘贴的。
![image](https://user-images.githubusercontent.com/25316350/233958709-400eb404-fe35-46bc-b147-656776fa7c18.png)

**Comment by zxiaowwqqwq** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/51262922/233959506-f2803738-aaf0-44da-b2a5-68f4a22553ef.png">

**Comment by symant233** [comment]
哥们 要点击这个开始翻译按钮后看终端报错信息的 
![image](https://user-images.githubusercontent.com/25316350/233959881-4bda4f34-8a1e-4410-8f17-c6fbe736d9d8.png)

**Comment by zxiaowwqqwq** [comment]
我的显示的和你不一样，没法点<img width="962" alt="image" src="https://user-images.githubusercontent.com/51262922/233960491-17c3d35a-26ed-44e1-a0bd-5468e3d02b6f.png">

**Comment by symant233** [comment]
等它加载完哥们。。。

可以点后点`开始翻译`，然后看终端是不是有翻译进度，如果出错了就把终端的报错截一下发这里，如果最后显示翻译完成了就点`加载线上数据`就行了。

**Comment by symant233** [comment]
估计解决了，如果觉得项目不错可以点个 ⭐Star，感谢~

**Comment by CoolLoong** [comment]
一样的问题 loading了10分钟还没loading好

**Comment by xindajizhewei** [comment]
> 估计解决了，如果觉得项目不错可以点个⭐Star，谢谢~

大佬，为什么我把破解文件放入老版mtool里面，按照流程弄完npm后，mtool的应用程序nw.exe打不开，点了没反应。

**Comment by symant233** [comment]
> 大佬，为什么我把破解文件放入老版mtool里面，按照流程弄完npm后，mtool的应用程序nw.exe打不开，点了没反应。

我也遇到了 不确定是不是作者程序里写了过期时间 或者新版本mtool对机器里的老版本做了处理 还是不小心联网被远程禁用了 我周末有空会看一下这个问题

--- update ---
我另一台电脑联网可以正常进工具，应该不是写了过期时间或者联网禁用。
另外，不要把本程序并入其他软件中，本程序应该在单独一个文件夹中使用。@xindajizhewei

**Comment by xindajizhewei** [comment]
![mmexport1692858415319](https://github.com/symant233/MTool_Cracker/assets/142999011/d43dff8c-7863-4e17-bf6f-1d9ea2d60ee4)
为什么我是这样的，哪里出了问题吗

**Comment by symant233** [comment]
@xindajizhewei 本项目是单独的程序 不应该放在其他文件夹内（比如MTool文件夹里），而应放在单独的文件夹中。

**Comment by xindajizhewei** [comment]
> 

![mmexport1692879464828](https://github.com/symant233/MTool_Cracker/assets/142999011/7699c996-ed9d-42d3-86fa-05e7f87903cb)
![mmexport1692879689898](https://github.com/symant233/MTool_Cracker/assets/142999011/0cae27d4-ff19-4476-b2f3-e66b3604d466)
![mmexport1692879693585](https://github.com/symant233/MTool_Cracker/assets/142999011/09617c03-da31-41d5-b901-e3d6f7133302)

![mmexport1692879697065](https://github.com/symant233/MTool_Cracker/assets/142999011/8f351101-4f3f-403b-8d3d-481bb9f0f978)
还是不行，运行了mtool上面的确没有了更新的提醒，但游戏翻译卡在这没动了，而且我用的腾讯翻译，上面翻译引擎也没有腾讯的字样。教程上说首次请求失败的东西也没遇见过

**Comment by xindajizhewei** [comment]
> 

![Uploading mmexport1692880877026.png…]()

**Comment by xindajizhewei** [comment]
> @xindajizhewei本项目是单独的程序不应该放在其他文件夹内（比如MTool文件夹里），而应放在单独的文件夹中。
![mmexport1692879464828](https://github.com/symant233/MTool_Cracker/assets/142999011/362c35f1-0f6d-4046-86fa-81a6de84f5f7)
![mmexport1692879689898](https://github.com/symant233/MTool_Cracker/assets/142999011/5b4dd20f-8480-468b-920b-f36d1c670013)
![mmexport1692879693585](https://github.com/symant233/MTool_Cracker/assets/142999011/ffb86f26-141f-4712-88d1-cd21c8cb0dd9)
![mmexport1692880877026](https://github.com/symant233/MTool_Cracker/assets/142999011/0bdb9bdf-070b-4c83-bd35-65f7be90dc5c)
![mmexport1692879697065](https://github.com/symant233/MTool_Cracker/assets/142999011/25a9e9c8-444a-4fe4-8cb4-9ab15d8bbc01)
还是不行，运行了mtool上说更新失败，游戏翻译卡在这没动了，我用的腾讯翻译上面翻译引擎也没有腾讯的字样。教程上说因为证书原因第一次请求失败的东西也遇见没有过

**Comment by symant233** [comment]
> 这步做了吗，感觉是这个的问题，搞完重启一下mtool和游戏
> > 首次使用此项目时, 由于使用了自签证书, 请求会失败 (更新那里会显示 Failed to fetch). 在工具里右键空白处点击检查, 在 Console 标签页会显示红色的报错, 点链接, 选显示更多继续访问. 之后只要不再换证书就不会再请求失败了.

@xindajizhewei

**Comment by xindajizhewei** [comment]
> > 这一步完成了吗，感觉是这个问题，搞一下mtool和游戏重启一下
> > > 首次使用此项目时，由于使用了自签证书，请求会失败（更新那里会显示Failed to fetch）。在工具栏右键空白处单击检查，在控制台标签页会显示红色的报错，点链接，选择显示更多继续访问。之后只要不再换证书就不会再请求失败了。
> 
> @xindajizhewei

![mmexport1692897160055](https://github.com/symant233/MTool_Cracker/assets/142999011/703eb388-4254-4150-8ab1-b3866ae13702)
为什么我打不开，挂了梯子也没用

**Comment by symant233** [comment]
@xindajizhewei 安装 certs/trs.cirno.biz.crt 到 个人 (双击打开->安装证书->存储位置:当前用户->将所有的证书都放入下列存储:个人->完成).

**Comment by xindajizhewei** [comment]
> @xindajizhewei安装 certs/trs.cirno.biz.crt 到个人（双击打开->安装证书->存储位置：当前用户->将所有的证书都放入以下存储：个人->完成）。

按照步骤做了的，还是不行。但我每次打开上面说明显示信息不足够，不能认证是这个原因吗
![mmexport1692926619234](https://github.com/symant233/MTool_Cracker/assets/142999011/33eea7b1-44a8-4444-b137-19ea32eddd3c)

**Comment by xindajizhewei** [comment]
> @xindajizhewei 安装 certs/trs.cirno.biz.crt 到 个人 (双击打开->安装证书->存储位置:当前用户->将所有的证书都放入下列存储:个人->完成).

大佬可以留个v或者q吗，这上面不是特别方便，应该最后两步了

**Comment by symant233** [comment]
你这个CONNECTION_REFUSED我怎么感觉是cracker服务没启动 @xindajizhewei

**Comment by xindajizhewei** [comment]
> 你这个CONNECTION_REFUSED我怎么感觉是cracker服务没启动@xindajizhewei

是么，我按照教程一步一步来的，该怎么启动呢。还是说我有步骤弄错了？有需要改的地方我都发图片在上面了

**Comment by symant233** [comment]
@CoolLoong 已更新2.0.0版，证书信任使用全新策略可以解决该问题，详见readme。
