### ISSUE TITLE
没找到腾讯翻译接口，是要自己写吗？

### ISSUE THREAD

**Issue by vbnshi** [symant233/MTool_Cracker#2]
我看简介上有写翻译借口但是我找不到，还是要自己写吗，没怎么接触过代码，感觉有点难度，可以给一个大概的教学吗，我用的彩云没有百度翻译接口那么复杂。

**Comment by symant233** [comment]
现在默认就是腾讯翻译啊

> 替换文件 example.env 内的 APPID 和 KEY 为你申请的应用信息,  替换后保存, 重命名此文件为 working.env. 
> 使用腾讯翻译则为 TENCENTID 和 TENCENTKEY（强烈建议用**腾讯翻译**，开通[机器翻译](https://console.cloud.tencent.com/tmt)后到[API密钥管理](https://console.cloud.tencent.com/cam/capi)查看SecretId和SecretKey）.

照上面说的把key填一下然后把文件名改好就可以用了

**Comment by symant233** [comment]
如果要用彩云翻译，得先参考彩云翻译的文档和`src/sdk.js`文件中的别的接口，先写好并测试通，再到`src/translator.js`中调用，仿照别的接口来调试。更改`src/index.js`中的[这一行](https://github.com/symant233/MTool_Cracker/blob/5e858b8e6d77e6c030b75eab80eda3e9bab40567/src/index.js#LL81C9-L81C9)为你的翻译函数名称。

**Comment by vbnshi** [comment]
> 现在默认就是腾讯翻译啊
> 
> > 替换文件 example.env 内的 APPID 和 KEY 为你申请的应用信息,  替换后保存, 重命名此文件为 working.env.
> > 使用腾讯翻译则为 TENCENTID 和 TENCENTKEY（强烈建议用**腾讯翻译**，开通[机器翻译](https://console.cloud.tencent.com/tmt)后到[API密钥管理](https://console.cloud.tencent.com/cam/capi)查看SecretId和SecretKey）.
> 
> 照上面说的把key填一下然后把文件名改好就可以用了

可是我看1.2.0里面的sdk.js文件里面只有百度的 如果我把 example.env 内的改成TENCENTID 和 TENCENTKEY也不能用腾讯接口翻译

**Comment by symant233** [comment]
奥奥不好意思 已经发了一个release1.3.0
