### ISSUE TITLE
请问大佬是不是更新地址改了，按教程运行服务后，启动后翻译界面显示需要更新

### ISSUE THREAD

**Issue by zeiyuL** [symant233/MTool_Cracker#3]
还是哪一步流程出错了，恳请大佬教导
![image](https://github.com/symant233/MTool_Cracker/assets/147472995/3276d31b-b8cd-4f51-9b3c-d5a0d0db736f)

**Comment by symant233** [comment]
检查一下:
1. MTool使用的是[此处](https://github.com/symant233/MTool_Cracker/releases/tag/v1.0.0)下载的老版本吗
2. 有没有更改hosts文件 (C:\Windows\System32\drivers\etc\hosts), 添加一行:
```
127.0.0.1 trs.cirno.biz
```

**Comment by zeiyuL** [comment]
12都有

**Comment by symant233** [comment]
感觉是hosts没生效，看下有没有开启工具首页的网络优化，关掉。另外保存hosts后重启一下MTool

**Comment by zeiyuL** [comment]
取消网络优化可以了，感激大佬
